use_frameworks!

target 'YTDevice_Example' do
    #pod 'YTDevice', :path => '../'
  pod 'YTDevice', :podspec => '../YTDevice.podspec'  # 指定podspec文件

  target 'YTDevice_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
